plugins {
	id "net.lopymine.mossy-plugin-core" version "$mossy_plugin_version"
}

mossyDependencies {
	minecraft = stonecutter.current.version.toString()
	mappings = "official"
	lombok = prop("base.lombok_version")

	fabricApi = prop("build.fabric_api")
	fabricLoader = prop("build.fabric_loader")

	forge = prop("build.forge")

	neoForge = prop("build.neoforge")
	parchment = prop("build.parchment")

	additional {
		//override("modCompileOnly", "yacl")
	}
}

processResources {
	if (stonecutter.compare(stonecutter.current.version, "1.21.9") >= 0) {
		fletchingTable.relocate(it, "assets/${prop("data.mod_id")}/spawn_areas_1_21_9/*.png -> ../spawn_areas")
	} else {
		exclude("assets/${prop("data.mod_id")}/spawn_areas_1_21_9/")
	}
}

configurations.forEach {
	it.resolutionStrategy {
		cacheChangingModulesFor(0, 'seconds')
	}
}

String prop(String key) {
	return findProperty(key).toString()
}
